#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/wmake/scripts/AllwmakeParseArguments

#------------------------------------------------------------------------------

echo "wmake $targetType dummy (mpi=$WM_MPLIB)"
wmake $targetType dummy

if [ -n "$FOAM_USE_MUI" ]
then
    ./Allwmake-mpi-MUI $targetType $*
else
    ./Allwmake-mpi $targetType $*
fi

#------------------------------------------------------------------------------
