#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory

#------------------------------------------------------------------------------

wclean dummy

if [ -n "$FOAM_USE_MUI" ]
then
    ./Allwclean-mpi-MUI
else
    ./Allwclean-mpi
fi

#------------------------------------------------------------------------------
