#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

runApplication reconstructParMesh -constant

runApplication reconstructPar

runApplication setExprFields -latestTime  ## -load-fields U

runApplication setExprBoundaryFields -latestTime  ## -load-fields '(U)'
touch foam.foam
#------------------------------------------------------------------------------
