#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------


restore0Dir

runApplication blockMesh

runApplication decomposePar

runParallel snappyHexMesh -overwrite

#find . -iname '*level*' -type f -delete

# Set the initial fields
restore0Dir -processor

runParallel topoSet
