#!/bin/sh

# Run from this directory
cd ${0%/*} || exit 1

domainFluid=${PWD}
domainStructure=${PWD}

# Ranks set to each domain
numProcsFluid=4
numProcsStructure=1

# Source OpenFOAM run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Create and copy data to run folder
./runCtrl/runDataFolderCreation

# Get application name for structure domain
solverStructure=structureDomainRun.py

# Get application name for fluid domain
# cd runData/fluidDomain
solverFluid=$(getApplication)
echo application is ${solverFluid}
# cd ../../

# Pre-processing
rm -rf 0/alpha.water  pos*; cp 0/alpha.water.orig 0/alpha.water; blockMesh ; setFields
decomposePar -force

echo -n "ParaSiF running..."
echo
# mpirun -np ${numProcsFluid} --output-filename Logs/coupledOutput ${solver1} -case ${domain1} -parallel : \
#       -np ${numProcs} ${solver2} -case ${domain2} -parallel
# mpirun -np ${numProcsFluid}  ${solverFluid} -case ${domainFluid} -parallel -coupled : \
mpirun  -np 4 ${solverFluid} -parallel -coupled  : -np 1  springDamping 
#mpirun  -np 4 ${solverFluid} -parallel
# mpirun -np 1  ReadFile : -np 1  pong

# ParaSiF case with OpenFOAM_MUI(C++)_MUI(python)_FEniCS parallel run
# mpirun -np ${numProcsFluid}  ${solverFluid} -case ${domainFluid} -parallel -coupled : \
#       -np ${numProcsStructure} -wdir ${domainStructure} python3.8 -m mpi4py ${solverStructure} \
      # > runData/logFiles/log.foamRun 2>&1 | tail -f runData/logFiles/log.foamRun
# :\
#        -np ${numProcsStructure} -wdir ${domainStructure} python3 -m mpi4py ${solverStructure}\
#         > runData/logFiles/log.foamRun 2>&1 | tail -f runData/logFiles/log.foamRun

echo "Done"

# Post-processing
#./runCtrl/postProcess

# ----------------------------------------------------------------- end-of-file
